server:
  port: 8081
dubbo:
  application:
    name: service-B
    qos-port: 33333
  registry:
    #address: zookeeper://localhost:2181
    address: multicast://224.5.6.7:1234?unicast=false
  protocol:
    name: dubbo
    port: 38887
    serialization: fastjson2
  consumer:
    check: false
    cache: false
    validation: true
    timeout: 3000
  provider:
    timeout: 3000
